### ISSUE TITLE
Ruby 3.0 Support?

### ISSUE THREAD

**Issue by metaskills** [aws/aws-lambda-ruby-runtime-interface-client#14]
Now that Ruby 2.5 is on its way out, I am hoping that at some point in time there is an official Ruby 3.0 Runtime. Am I correct that this runtime interface will have to be updated at well? I ran the unit tests and only saw this one time format error.

```
  1) Failure:
HarnessTests#test_dependencies [/Users/kencollins/Repositories/aws-lambda-ruby-runtime-interface-client/test/unit/harness_test.rb:88]:
--- expected
+++ actual
@@ -1 +1 @@
-"{\"tomorrow\":\"2018-10-09T11:34:20.000+01:00\"}"
+"{\"tomorrow\":\"2018-10-09 11:34:20 +0100\"}"
```

**Comment by djpate** [comment]
We've been using it on prod. No issues so far.

**Comment by jstefek** [comment]
When using with ruby 3.1 I get following error after the execution of my function finishes:

```
Critical exception from handler
{
"errorMessage": "uninitialized constant #<Class:AwsLambda::Marshaller>::StringIO\n\n        when StringIO, IO\n             ^^^^^^^^",
"errorType": "Function<NameError>",
"stackTrace": [
"/some/path/vendor/bundle/ruby/3.1.0/gems/aws_lambda_ric-2.0.0/lib/aws_lambda_ric/aws_lambda_marshaller.rb:27:in `marshall_response'",
"/some/path/vendor/bundle/ruby/3.1.0/gems/aws_lambda_ric-2.0.0/lib/aws_lambda_ric/lambda_handler.rb:31:in `call_handler'",
"/some/path/vendor/bundle/ruby/3.1.0/gems/aws_lambda_ric-2.0.0/lib/aws_lambda_ric.rb:81:in `run_user_code'",
"/some/path/vendor/bundle/ruby/3.1.0/gems/aws_lambda_ric-2.0.0/lib/aws_lambda_ric.rb:59:in `start_runtime_loop'",
"/some/path/vendor/bundle/ruby/3.1.0/gems/aws_lambda_ric-2.0.0/lib/aws_lambda_ric.rb:42:in `run'",
"/some/path/vendor/bundle/ruby/3.1.0/gems/aws_lambda_ric-2.0.0/lib/aws_lambda_ric/bootstrap.rb:35:in `bootstrap_handler'",
"/some/path/vendor/bundle/ruby/3.1.0/gems/aws_lambda_ric-2.0.0/lib/aws_lambda_ric/bootstrap.rb:8:in `start'",
"/some/path/vendor/bundle/ruby/3.1.0/gems/aws_lambda_ric-2.0.0/bin/aws_lambda_ric:10:in `<top (required)>'",
"/some/path/vendor/bundle/ruby/3.1.0/bin/aws_lambda_ric:25:in `load'",
"/some/path/vendor/bundle/ruby/3.1.0/bin/aws_lambda_ric:25:in `<main>'"
]
}
Init error when loading handler
{
"errorMessage": "wrong number of arguments (given 4, expected 2..3)",
"errorType": "Init<ArgumentError>",
"stackTrace": [
"/some/path/vendor/bundle/ruby/3.1.0/gems/aws_lambda_ric-2.0.0/lib/aws_lambda_ric.rb:109:in `send_error_response'",
"/some/path/vendor/bundle/ruby/3.1.0/gems/aws_lambda_ric-2.0.0/lib/aws_lambda_ric.rb:98:in `rescue in run_user_code'",
"/some/path/vendor/bundle/ruby/3.1.0/gems/aws_lambda_ric-2.0.0/lib/aws_lambda_ric.rb:77:in `run_user_code'",
"/some/path/vendor/bundle/ruby/3.1.0/gems/aws_lambda_ric-2.0.0/lib/aws_lambda_ric.rb:59:in `start_runtime_loop'",
"/some/path/vendor/bundle/ruby/3.1.0/gems/aws_lambda_ric-2.0.0/lib/aws_lambda_ric.rb:42:in `run'",
"/some/path/vendor/bundle/ruby/3.1.0/gems/aws_lambda_ric-2.0.0/lib/aws_lambda_ric/bootstrap.rb:35:in `bootstrap_handler'",
"/some/path/vendor/bundle/ruby/3.1.0/gems/aws_lambda_ric-2.0.0/lib/aws_lambda_ric/bootstrap.rb:8:in `start'",
"/some/path/vendor/bundle/ruby/3.1.0/gems/aws_lambda_ric-2.0.0/bin/aws_lambda_ric:10:in `<top (required)>'",
"/some/path/vendor/bundle/ruby/3.1.0/bin/aws_lambda_ric:25:in `load'",
"/some/path/vendor/bundle/ruby/3.1.0/bin/aws_lambda_ric:25:in `<main>'"
]
}
```
so I had to set **Retry attempts** to 0 for the lambda.

**Comment by rberger** [comment]
I'm not clear if the current lambda runtime does support Ruby 3.x or not. This thread seems to be saying it does, but the README says:
> The Ruby Runtime Interface Client package currently supports Ruby versions:
>
>    * 2.5.x up to and including 2.7.x

**Comment by rberger** [comment]
Will there ever be Ruby 3.x support?

**Comment by rberger** [comment]
If Ruby 3x support is not imminent, any pointers on building a custom ruby 3 runtime?

**Comment by rjhornsby** [comment]
> If Ruby 3x support is not imminent, any pointers on building a custom ruby 3 runtime?

Ruby 2.7 is EOL in 3 months. Ruby 3.0 was released GA two years ago. I hesitate to throw my hands up and say we're not getting Ruby 3.x support for our Lambda functions, but it certainly seems like if it was going to be a thing it should have been done by now.

Two years after the GA release I think we can safely agree that Ruby 3.0 isn't bleeding edge. I also understand that NodeJS and Python are all the rage (and there's nothing wrong with Python), but I have to imagine that we're far from alone in being a mostly Ruby shop because we're a Chef shop - which naturally means also doing most of our non-chef work in Ruby.

**Comment by metaskills** [comment]
I can concur this gem works fine with any modern Ruby I have thrown at it. We use the Ruby RIC for all our K8s images to get EventBridge rules. I also updated the Rails on Lambda (Lamby) cokoiecuter project using Debian images with the RIC on Ruby 3.1, works great. https://github.com/customink/lamby-cookiecutter/pull/21

Hope that helps!

**Comment by dimasusername** [comment]
Ruby 3 aside, we desperately need a fresh release, monkey-patching fixes as mentioned here (kudos to @jstefek) is not the way to go

**Comment by romiras** [comment]
Despite a request for Ruby 3 support being made a long time ago, this issue is no longer relevant since Ruby 3 is unfortunately EOL.

**Comment by rjhornsby** [comment]
> Despite a request for Ruby 3 support being made a long time ago, this issue is no longer relevant since Ruby 3 is unfortunately EOL.

To be more specific, Ruby 3.0 is deprecated. Ruby 3.x isn't going anywhere and is active development, with 3.3 being current.

https://endoflife.date/ruby

**Comment by mullermp** [comment]
This should be resolved with https://rubygems.org/gems/aws_lambda_ric and the latest main branch.
