### ISSUE TITLE
Wrong number of arguments error in `send_error_response`

### ISSUE THREAD

**Issue by brunze** [aws/aws-lambda-ruby-runtime-interface-client#15]
When my functions raise errors I get the following additional error printed out to the logs:

```
}
  Init error when loading handler
  {
    "errorMessage": "wrong number of arguments (given 4, expected 2..3)",
    "errorType": "Init<ArgumentError>",
    "stackTrace": [
      "/usr/local/bundle/gems/aws_lambda_ric-1.0.2/lib/aws_lambda_ric.rb:109:in `send_error_response'",
      "/usr/local/bundle/gems/aws_lambda_ric-1.0.2/lib/aws_lambda_ric.rb:98:in `rescue in run_user_code'",
      "/usr/local/bundle/gems/aws_lambda_ric-1.0.2/lib/aws_lambda_ric.rb:77:in `run_user_code'",
      "/usr/local/bundle/gems/aws_lambda_ric-1.0.2/lib/aws_lambda_ric.rb:59:in `start_runtime_loop'",
      "/usr/local/bundle/gems/aws_lambda_ric-1.0.2/lib/aws_lambda_ric.rb:42:in `run'",
      "/usr/local/bundle/gems/aws_lambda_ric-1.0.2/lib/aws_lambda_ric/bootstrap.rb:35:in `bootstrap_handler'",
      "/usr/local/bundle/gems/aws_lambda_ric-1.0.2/lib/aws_lambda_ric/bootstrap.rb:8:in `start'",
      "/usr/local/bundle/gems/aws_lambda_ric-1.0.2/bin/aws_lambda_ric:10:in `<top (required)>'",
      "/usr/local/bundle/bin/aws_lambda_ric:23:in `load'",
      "/usr/local/bundle/bin/aws_lambda_ric:23:in `<main>'"
    ]
}
```

I'm using the RIC with the Ruby Alpine docker images. Ruby version is 2.7.3p183.

It looks like a method signature mismatch in:

https://github.com/aws/aws-lambda-ruby-runtime-interface-client/blob/d5cfe4f7e9d52e02c93cbfdbc6da2ab0023a033c/lib/aws_lambda_ric.rb#L109

I monkey patched it to `def send_error_response(lambda_invocation, err, exit_code = nil, runtime_loop_active = true)` (last parameter converted to positional parameter) and that seemed to fix it.

Either that or the call sites for `send_error_response` need to change.

**Comment by djpate** [comment]
Add to fork it aswell. Could this be addressed?

**Comment by avgerin0s** [comment]
Are there any plans on releasing a version with the fix?

**Comment by jordan-brough** [comment]
This was fixed over a year ago in https://github.com/aws/aws-lambda-ruby-runtime-interface-client/pull/20 but a new version of the gem hasn't been published still.

**Comment by mullermp** [comment]
Closing as a new gem version had been published.
