### ISSUE TITLE
Runtime error when using bundle exec aws_lambda_ric from ENTRYPOINT

### ISSUE THREAD

**Issue by cristianpaul0** [aws/aws-lambda-ruby-runtime-interface-client#23]
I'm installing the aws_lambda_ric using bundle along other gems  (s3) the application needs in the Dockerfile

I tried then this:

ENTRYPOINT ["bundle", "exec", "aws_lambda_ric"]

Lambda fails:

```
{
  "errorMessage": "RequestId: 62a1664f-58dc-48d7-8f80-0ac023a8fdd1 Error: Runtime exited with error: exit status 1",
  "errorType": "Runtime.ExitError"
}
```

and the full log:

```
**/usr/local/gems/bundler-2.3.22/lib/bundler/definition.rb:518:in `materialize': Could not find aws-sdk-s3-1.114.0, aws_lambda_ric-2.0.0, rspec-3.11.0, aws-sdk-core-3.152.0, aws-sdk-kms-1.58.0, aws-sigv4-1.5.1, rspec-core-3.11.0, rspec-expectations-3.11.1, rspec-mocks-3.11.1, aws-eventstream-1.2.0, aws-partitions-1.634.0, jmespath-1.6.1, rspec-support-3.11.1, diff-lcs-1.5.0 in locally installed gems (Bundler::GemNotFound)
from /usr/local/gems/bundler-2.3.22/lib/bundler/definition.rb:197:in `specs'
from /usr/local/gems/bundler-2.3.22/lib/bundler/definition.rb:254:in `specs_for'
from /usr/local/gems/bundler-2.3.22/lib/bundler/runtime.rb:18:in `setup'
from /usr/local/gems/bundler-2.3.22/lib/bundler.rb:162:in `setup'
from /usr/local/gems/bundler-2.3.22/lib/bundler/setup.rb:20:in `block in <top (required)>'
from /usr/local/gems/bundler-2.3.22/lib/bundler/ui/shell.rb:136:in `with_level'
from /usr/local/gems/bundler-2.3.22/lib/bundler/ui/shell.rb:88:in `silence'
from /usr/local/gems/bundler-2.3.22/lib/bundler/setup.rb:20:in `<top (required)>'
from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
/usr/local/gems/bundler-2.3.22/lib/bundler/definition.rb:518:in `materialize': Could not find aws-sdk-s3-1.114.0, aws_lambda_ric-2.0.0, rspec-3.11.0, aws-sdk-core-3.152.0, aws-sdk-kms-1.58.0, aws-sigv4-1.5.1, rspec-core-3.11.0, rspec-expectations-3.11.1, rspec-mocks-3.11.1, aws-eventstream-1.2.0, aws-partitions-1.634.0, jmespath-1.6.1, rspec-support-3.11.1, diff-lcs-1.5.0 in locally installed gems (Bundler::GemNotFound)
from /usr/local/gems/bundler-2.3.22/lib/bundler/definition.rb:197:in `specs'
from /usr/local/gems/bundler-2.3.22/lib/bundler/definition.rb:254:in `specs_for'
from /usr/local/gems/bundler-2.3.22/lib/bundler/runtime.rb:18:in `setup'
from /usr/local/gems/bundler-2.3.22/lib/bundler.rb:162:in `setup'
from /usr/local/gems/bundler-2.3.22/lib/bundler/setup.rb:20:in `block in <top (required)>'
from /usr/local/gems/bundler-2.3.22/lib/bundler/ui/shell.rb:136:in `with_level'
from /usr/local/gems/bundler-2.3.22/lib/bundler/ui/shell.rb:88:in `silence'
from /usr/local/gems/bundler-2.3.22/lib/bundler/setup.rb:20:in `<top (required)>'
from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
START RequestId: 62a1664f-58dc-48d7-8f80-0ac023a8fdd1 Version: $LATEST
END RequestId: 62a1664f-58dc-48d7-8f80-0ac023a8fdd1
REPORT RequestId: 62a1664f-58dc-48d7-8f80-0ac023a8fdd1	Duration: 517.48 ms	Billed Duration: 518 ms	Memory Size: 1024 MB	Max Memory Used: 24 MB	
RequestId: 62a1664f-58dc-48d7-8f80-0ac023a8fdd1 Error: Runtime exited with error: exit status 1
Runtime.ExitError**
```

My Gemfile looks like this:

```
# frozen_string_literal: true

ruby '2.7.0' 

source 'https://rubygems.org'

git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }

gem 'aws-sdk-s3'
gem 'aws_lambda_ric'

group :development, :test do
  gem 'rspec'
end
```

**Comment by yegor256** [comment]
@cristianpaul0 it would be helpful if you show your `Dockerfile` too

**Comment by mullermp** [comment]
Please set your entry point to the path of your executable - there is an example in the README. Closing this as a stale issue. Please re-open if there is still an issue.
