### ISSUE TITLE
zeitwerk eager_load error

### ISSUE THREAD

**Issue by tadao** [aws/aws-lambda-ruby-runtime-interface-client#25]
I'm getting some errors.
Anyone help?

----
rails 6.1.7
----

`${root}/lambda_function/rails_runner_handler/app.rb`
```
require_relative '../../config/environment'

module LambdaFunction
  module RailsRunnerHandler
    class App
      def self.process(event:, context:)
        "Success"
        # task = event['task']
        # eval("#{task}")
      end
    end
  end
end
```

`Dockerfile`
```

FROM myapp

COPY Gemfile /app/Gemfile
COPY Gemfile.lock /app/Gemfile.lock

WORKDIR /app
RUN bundle install -j4

COPY . /app
RUN bundle --version

WORKDIR /app/lambda_function/rails_runner_handler/

ENTRYPOINT ["/bundle/bin/aws_lambda_ric"]
CMD ["app.LambdaFunction::RailsRunnerHandler::App.process"]
```

Error log
```
"/bundle/ruby/2.7.0/gems/zeitwerk-2.6.6/lib/zeitwerk/loader/eager_load.rb:16:in `each'",
"/bundle/ruby/2.7.0/gems/zeitwerk-2.6.6/lib/zeitwerk/loader/eager_load.rb:16:in `block in eager_load'",
"/bundle/ruby/2.7.0/gems/zeitwerk-2.6.6/lib/zeitwerk/loader/eager_load.rb:10:in `synchronize'",
"/bundle/ruby/2.7.0/gems/zeitwerk-2.6.6/lib/zeitwerk/loader/eager_load.rb:10:in `eager_load'",
"/bundle/ruby/2.7.0/gems/zeitwerk-2.6.6/lib/zeitwerk/loader.rb:296:in `block in eager_load_all'",
"/bundle/ruby/2.7.0/gems/zeitwerk-2.6.6/lib/zeitwerk/loader.rb:294:in `each'",
"/bundle/ruby/2.7.0/gems/zeitwerk-2.6.6/lib/zeitwerk/loader.rb:294:in `eager_load_all'",
"/bundle/ruby/2.7.0/gems/railties-6.1.7/lib/rails/application/finisher.rb:133:in `block in <module:Finisher>'",
"/bundle/ruby/2.7.0/gems/railties-6.1.7/lib/rails/initializable.rb:32:in `instance_exec'",
"/bundle/ruby/2.7.0/gems/railties-6.1.7/lib/rails/initializable.rb:32:in `run'",
"/bundle/ruby/2.7.0/gems/railties-6.1.7/lib/rails/initializable.rb:61:in `block in run_initializers'",
"/usr/local/lib/ruby/2.7.0/tsort.rb:228:in `block in tsort_each'",
"/usr/local/lib/ruby/2.7.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'",
"/usr/local/lib/ruby/2.7.0/tsort.rb:431:in `each_strongly_connected_component_from'",
"/usr/local/lib/ruby/2.7.0/tsort.rb:349:in `block in each_strongly_connected_component'",
"/usr/local/lib/ruby/2.7.0/tsort.rb:347:in `each'",
"/usr/local/lib/ruby/2.7.0/tsort.rb:347:in `call'",
"/usr/local/lib/ruby/2.7.0/tsort.rb:347:in `each_strongly_connected_component'",
"/usr/local/lib/ruby/2.7.0/tsort.rb:226:in `tsort_each'",
"/usr/local/lib/ruby/2.7.0/tsort.rb:205:in `tsort_each'",
"/bundle/ruby/2.7.0/gems/railties-6.1.7/lib/rails/initializable.rb:60:in `run_initializers'",
"/bundle/ruby/2.7.0/gems/railties-6.1.7/lib/rails/application.rb:391:in `initialize!'",
"/home/ubuntu/tofu/lambda_function/rails_runner_handler/app.rb:10:in `process'",
"/bundle/ruby/2.7.0/gems/aws_lambda_ric-2.0.0/lib/aws_lambda_ric/lambda_handler.rb:26:in `call_handler'",
"/bundle/ruby/2.7.0/gems/aws_lambda_ric-2.0.0/lib/aws_lambda_ric.rb:81:in `run_user_code'",
"/bundle/ruby/2.7.0/gems/aws_lambda_ric-2.0.0/lib/aws_lambda_ric.rb:59:in `start_runtime_loop'",
"/bundle/ruby/2.7.0/gems/aws_lambda_ric-2.0.0/lib/aws_lambda_ric.rb:42:in `run'",
"/bundle/ruby/2.7.0/gems/aws_lambda_ric-2.0.0/lib/aws_lambda_ric/bootstrap.rb:35:in `bootstrap_handler'",
"/bundle/ruby/2.7.0/gems/aws_lambda_ric-2.0.0/lib/aws_lambda_ric/bootstrap.rb:8:in `start'",
"/bundle/ruby/2.7.0/gems/aws_lambda_ric-2.0.0/bin/aws_lambda_ric:10:in `<top (required)>'",
"/bundle/bin/aws_lambda_ric:27:in `load'",
"/bundle/bin/aws_lambda_ric:27:in `<main>'"
```

Thanks.

**Comment by tadao** [comment]
Sorry. There was a setting error.
